Address Leaks and Go Vet Tool Issues
google/cloud-android-orchestration pull request #238
Opened 2023-11-08 18:33 UTC by Mahmod

This commit fixes various leaks and other errors identified by the go vet tool across the Golang codebase.

Please review this pull request carefully , since I only validated the suggested fixes through `go vet ./...` command .
I'm not familiar with the functional testing that assure the functionality of my suggestions .

Bug: b/309808700

2023-11-08 22:09 UTC, jemoreira requested changes

2023-11-08 22:09 UTC, jemoreira commented on pkg/client/httputils.go
> +	}()
This isn't needed. The loop above doesn't break until the channel is drained.

2023-11-08 22:09 UTC, jemoreira commented on pkg/client/httputils.go
>  				returnErr = err
you can improve this line by making `returnErr` a `multierror` and appending each received error to it.

2023-11-08 22:09 UTC, jemoreira commented on pkg/client/httputils.go
> +	// ensure cancel is called even in the case of an error
Actually, the existing code only calls `cancel` when there are errors. This ensures it's called when there are NO errors too.

2023-11-20 18:00 UTC, Mahmod commented
This issue is resolved by @jemoreira in different Pr , no longer needed

2023-11-20 18:00 UTC, closed without merging