Fallback to upload current dir when running cvdr create with local_image
google/cloud-android-orchestration pull request #291
Opened 2024-03-22 07:58 UTC by 0405ysj

2024-03-22 08:02 UTC, 0405ysj commented
Interested thing was, it took only about 5-7 mins to upload artifacts & running CF instance. Probably, would it be caused by using public stun server(stun.l.google.com)?

2024-03-22 08:10 UTC, ikicha commented
Interesting, I think it might be due to socks5 proxy rather than stun server. can you benchmark network bandwidth with socks5?

2024-03-22 08:35 UTC, 0405ysj commented
I roughly checked with our hybrid one, and it took about 12-13 mins. And `super.img` was about 4.7G. Seems like the bandwidth is about 6MB/s or 48Mbps

2024-03-22 20:48 UTC, jemoreira requested changes

2024-03-22 20:48 UTC, jemoreira commented on pkg/cli/cvd.go
> +	if err == nil {
The code pattern for this function should be roughly:
```
cvd, err := createCVDFromBuiltSource(...)
if errors.Is(err, NotInAndroidSourceErr) {
  return createCVDFromCurrentDir(...)
}
return cvd, err
```
I think encapsulating both flows into their own functions will increase readability.

2024-03-22 21:44 UTC, ser-io commented
Uploading everything from the current directory with no validation is a big responsibility to pass to the final user, this could end up in undesirable behaviors, for example uploading personal files.

2024-03-25 01:46 UTC, ikicha commented
IIUC, imgs.zip has required_image file inside. We can use that to list up files which we want to send.

2024-03-25 02:02 UTC, 0405ysj commented
> Wrote https://github.com/google/cloud-android-orchestration/pull/292 where we need to be upfront with what's going to be uploaded, it also offers more flexibility to build instances with mixed artifacts, as we just need to change the artifacts sources file.

Should I close this PR then? I saw the PR you've created, and this and that contains duplicated contents. Seems your PR covers wider purposes.


> IIUC, imgs.zip has required_image file inside. 

Do we? I unpacked CF image zip file downloaded from ci.android.com, and there was no `required_image`.

2024-03-25 02:08 UTC, ikicha commented
ah, sorry, require_image exists in PRODUCT_OUT, not imgs.zip

2024-03-25 18:19 UTC, ser-io commented
yes, let's close this one, thanks!

2024-03-26 01:02 UTC, closed without merging