Prompt the client to set an username for http basic auth.
google/cloud-android-orchestration pull request #302
Opened 2024-04-15 08:06 UTC by denniscy1993

- The cloud orchestrator server that uses HTTPBasicAccountManager would send a 401 unauthorized response to the client to popup the login window.

2024-04-15 08:09 UTC, denniscy1993 commented
This PR is to address b/333545755.

2024-04-15 08:48 UTC, 0405ysj approved these changes

2024-04-15 08:48 UTC, 0405ysj commented on pkg/app/accounts/basic.go
> +		return nil, nil
nit: Don't we need an error here? This seems like a refactoring, but error looks gone.

2024-04-15 09:03 UTC, denniscy1993 commented on pkg/app/accounts/basic.go
> +		return nil, nil
Actually `app.go` will send `apperr.NewUnauthenticatedError("Authentication required", nil)` when it receives  a `nil` user returned by  `UserFromRequest`. We need this 401 unauthorized error to popup the login window at the client side.

2024-04-15 15:51 UTC, ser-io commented on pkg/app/accounts/basic.go
> +		return nil, nil
basic auth is considered a bad practice, it could work in a very controlled environment as a POC, which is the use case here, having said so, we should never prompt the user for a password.  please if this popup have password input, let's discard this PR as users can mistakenly enter a valid password which is not wanted or needed in our system.

2024-04-15 15:59 UTC, ser-io requested changes
we should not prompt users for a password, it's not needed and users can mistakenly provide one.

2024-05-10 08:50 UTC, denniscy1993 commented
Thanks for the suggestions, I would close this PR.

2024-05-10 08:50 UTC, closed without merging