Rename HTTPBasicAccountManager to UsernameOnlyAccountManager.
google/cloud-android-orchestration pull request #314
Opened 2024-05-21 17:27 UTC by denniscy1993

- Renaming this account manager because it was designed for closed deployed cloud orchestrator. Although we leverage the HTTP basic authentication, only username is used.

- Tests:
  - `cvdr create`
  - `cvdr list`
  - `cvdr delete`

2024-05-21 17:31 UTC, denniscy1993 commented
Note: I did not change the name of `AuthnOpts.HTTPBasic` at `pkg/client/client.go` because I think this is related to how we build the HTTP requests. We are still leveraging the HTTP basic authentication while building requests even though the name of AM is being changed.

2024-05-21 20:55 UTC, ser-io requested changes
let's keep this PR focused on the cloud orchestator (server) code only. 

we can rename the concepts in cvdr (client) in a different PR, although I think it's not necessary in this case.

2024-05-21 23:50 UTC, 0405ysj approved these changes
LGTM, but please resolve Sergio's comment in advance.

2024-05-22 15:04 UTC, denniscy1993 commented
> let's keep this PR focused on the cloud orchestator (server) code only.
> 
> we can rename the concepts in cvdr (client) in a different PR, although I think it's not necessary in this case.

Done, and agree that we don't need to rename the client.

2024-05-22 16:57 UTC, ser-io approved these changes

2024-05-23 01:55 UTC, merged