feat: add Cloud Run deployment
google/cloud-android-orchestration pull request #376
Opened 2024-11-20 12:49 UTC by kunzese

This PR adds the Terraform setup and the necessary changes to Cloud Orchestrator to be deployed on Cloud Run protected by IAP. Additionally it includes the possibility to use GCE instances with private IPs only.

2024-11-20 12:53 UTC, kunzese commented
@gleichda FYI

2024-11-21 17:56 UTC, ser-io requested changes

2024-11-21 17:56 UTC, ser-io commented on scripts/gcp/app/conf.toml.tmpl
> +Type = "IAP"
Let's keep App Engine deployment config with `GCP` for know as there's no documentation to enable IAP for the App Engine deployment publicly available yet.

2024-11-21 17:56 UTC, ser-io commented on terraform/.terraform.lock.hcl
is this file needed in the repo?

2024-11-21 17:56 UTC, ser-io commented on terraform/README.md
let's move the new `terraform` directory under `scripts/gcp/cloudrun/`

2024-11-22 07:37 UTC, kunzese commented on terraform/.terraform.lock.hcl
Yes i is advised to commit this file too. It is like the `go.sum` file a record of all dependencies and their versions.

2024-11-22 20:20 UTC, ser-io approved these changes

2024-11-22 20:20 UTC, ser-io commented on pkg/app/instances/gce.go
> +	UsePrivateIP         bool
let's default to private ip only, and add the config parameter to enabling external ip.

2024-11-25 17:19 UTC, ser-io approved these changes

2024-12-04 17:17 UTC, ser-io requested changes
Rebase the `cloudrun-clean` branch on top of main instead rather than having a merge commit.

2024-12-04 19:14 UTC, merged