Allow to specify boot disk size for GCE instances and auto delete boot disk
google/cloud-android-orchestration pull request #377
Opened 2024-11-21 14:42 UTC by gleichda

- Add option for GCE To specify boot disk size; It will fall back to the image size if unset (Keeping the same default)
- Move the `BootDiskSizeGB` to be GCP Only as it is used nowhere else and is GCP specific
- Configure Boot disks to auto delete to properly clean up

New config would look like:
```
SystemDefaultService = "dockerIM"
[Services.dockerIM]
ServiceURL = "https://myservice.example.com"
Zone = "europe-west3-a"

Host={
	GCP={
		MachineType = "n1-standard-4",
		MinCPUPlatform = "Intel Haswell",
		BootDiskSizeGB = 100
	}
}
Authn={
	OIDCToken={
		TokenFile = "/tmp/cvdr_oidc.token"
	}
}
```

2024-11-21 18:00 UTC, ser-io requested changes
let's split this PR into two commits: one for auto delete boot disk and the other for boot disk size.

2024-11-21 18:52 UTC, gleichda commented
Tested the performance impact of setting the disk size via Cloud Orchestrator and the additional startup latency is negligible
<img width="858" alt="image" src="https://github.com/user-attachments/assets/693c2dc4-ea04-45ed-a8b4-ac7cad0e7155">

2024-11-21 19:18 UTC, ser-io commented on pkg/cli/cli.go
> +	gcpBootDiskSizeGB 	  = "gcp_boot_disk_size_gb"
nit: run go lint `gofmt`

2024-11-25 17:15 UTC, ser-io approved these changes

2024-11-26 14:14 UTC, merged