Support connect agent configuration in cvdr.toml
google/cloud-android-orchestration pull request #390
Opened 2024-12-24 05:28 UTC by 0405ysj

2024-12-24 05:35 UTC, 0405ysj commented
While working on this PR, I found a weird point about flag setting before running subcommand. For some configurations, it brings config of default service if config of speficied service is empty IIUC. Is it known issue? I feel we need to refactor around here, not to bring configuration value of different service.

2025-01-06 20:26 UTC, ser-io requested changes

2025-01-06 20:26 UTC, ser-io commented on pkg/cli/cli.go
> +		connectAgent := flags.CreateCVDOpts.ConnectAgent
Initialize variable with webrtc agent value `connectAgent := ConnectionWebRTCAgentCommandName` and update it with the flag value if it's not empty. I think it is easier to read.

2025-01-06 20:26 UTC, ser-io commented on pkg/cli/cli.go
> +	connectAgent := flags.connectAgent
ditto.

2025-01-06 20:26 UTC, ser-io commented on scripts/on-premises/single-server/cvdr.toml
> +ConnectAgent = "websocket_agent"
can we use "websocket" value? In `"websocket_agent"`, suffix "_agent" is redundant.

2025-01-06 20:26 UTC, ser-io commented on scripts/on-premises/single-server/cvdr.toml
> +ServiceURL = "http://100.114.242.57:8080"
nit: revert to localhost.

2025-01-06 20:26 UTC, ser-io commented on scripts/on-premises/single-server/cvdr.toml
> +Proxy = "socks5://localhost:1337"
nit: revert to "${SOCKS5_PORT}"

2025-01-07 00:36 UTC, 0405ysj commented on scripts/on-premises/single-server/cvdr.toml
> +ServiceURL = "http://100.114.242.57:8080"
Sorry for the mistake, done.

2025-01-07 00:36 UTC, 0405ysj commented on scripts/on-premises/single-server/cvdr.toml
> +Proxy = "socks5://localhost:1337"
Done.

2025-01-07 00:37 UTC, 0405ysj commented on scripts/on-premises/single-server/cvdr.toml
> +ConnectAgent = "websocket_agent"
Add one more commit for renaming connect agents.

2025-01-07 00:43 UTC, 0405ysj commented on pkg/cli/cli.go
> +		connectAgent := flags.CreateCVDOpts.ConnectAgent
Done.

2025-01-07 00:43 UTC, 0405ysj commented on pkg/cli/cli.go
> +	connectAgent := flags.connectAgent
Done.

2025-01-07 14:36 UTC, ser-io approved these changes

2025-01-08 01:20 UTC, merged